/**
 * Messaging System Type Definitions (Backend)
 * Backend types for Phase 2 & 3 Messaging implementation
 */

import { Socket } from 'socket.io';
import { User } from '@prisma/client';

// Note: Conversation, DirectMessage, Contact are generated by Prisma
// These types are defined in schema.prisma and available via @prisma/client
// when `npx prisma generate` is run

// ============================================
// WEBSOCKET TYPES
// ============================================

/**
 * Extended Socket type with user info
 */
export interface AuthenticatedSocket extends Socket {
  userId?: string;
  userEmail?: string;
  userRole?: string;
}

/**
 * WebSocket event handler type
 */
export type WebSocketEventHandler = (
  socket: AuthenticatedSocket,
  io: any,
  data?: any
) => Promise<void>;

/**
 * WebSocket message payload from client
 */
export interface ClientMessagePayload {
  conversationId: string;
  content: string;
  messageType?: string;
}

/**
 * WebSocket read receipt payload
 */
export interface ClientReadPayload {
  conversationId: string;
  messageId: string;
}

/**
 * WebSocket edit message payload
 */
export interface ClientEditPayload {
  messageId: string;
  conversationId: string;
  content: string;
}

/**
 * WebSocket delete message payload
 */
export interface ClientDeletePayload {
  messageId: string;
  conversationId: string;
}

/**
 * WebSocket typing indicator payload
 */
export interface ClientTypingPayload {
  conversationId: string;
  isTyping: boolean;
}

// ============================================
// DATABASE ENTITY TYPES
// ============================================

/**
 * Contact with related data
 * Generic type for flexibility with Prisma models
 */
export interface ContactWithUser {
  id: string;
  userId: string;
  contactUserId: string;
  contactType: string;
  addedAt: Date;
  notes?: string;
  contactUser?: User;
  user?: User;
}

/**
 * Conversation with participants
 * Generic type for flexibility with Prisma models
 */
export interface ConversationWithParticipants {
  id: string;
  participant1Id: string;
  participant2Id: string;
  createdAt: Date;
  updatedAt: Date;
  participant1?: User;
  participant2?: User;
  messages?: DirectMessageWithSender[];
}

/**
 * Direct message with sender
 * Generic type for flexibility with Prisma models
 */
export interface DirectMessageWithSender {
  id: string;
  conversationId: string;
  senderId: string;
  content: string;
  messageType: string;
  isEdited: boolean;
  isDeleted: boolean;
  readAt?: Date;
  createdAt: Date;
  updatedAt: Date;
  sender?: User;
}

// ============================================
// SERVICE TYPES
// ============================================

/**
 * Contact service response
 */
export interface ContactServiceResponse {
  success: boolean;
  data?: any;
  error?: string;
}

/**
 * Conversation service response
 */
export interface ConversationServiceResponse {
  success: boolean;
  conversation?: ConversationWithParticipants;
  error?: string;
}

/**
 * Message service response
 */
export interface MessageServiceResponse {
  success: boolean;
  message?: DirectMessageWithSender;
  messages?: DirectMessageWithSender[];
  error?: string;
}

// ============================================
// AUTHORIZATION TYPES
// ============================================

/**
 * Authorization check result
 */
export interface AuthorizationResult {
  authorized: boolean;
  reason?: string;
}

/**
 * Contact authorization context
 */
export interface ContactAuthContext {
  userId: string;
  targetUserId: string;
  role?: string;
}

/**
 * Message authorization context
 */
export interface MessageAuthContext {
  userId: string;
  conversationId: string;
  role?: string;
}

// ============================================
// NOTIFICATION TYPES
// ============================================

/**
 * Message notification
 */
export interface MessageNotification {
  type: 'message:new' | 'message:edit' | 'message:delete' | 'message:read';
  conversationId: string;
  messageId?: string;
  senderId?: string;
  senderName?: string;
  content?: string;
  timestamp: string;
}

/**
 * Status notification
 */
export interface StatusNotification {
  type: 'user:online' | 'user:offline';
  userId: string;
  userName: string;
  timestamp: string;
}

/**
 * Typing notification
 */
export interface TypingNotification {
  type: 'typing:start' | 'typing:stop';
  conversationId: string;
  userId: string;
  userName: string;
  timestamp: string;
}

// ============================================
// ERROR TYPES
// ============================================

/**
 * Application error
 */
export class AppError extends Error {
  constructor(
    public statusCode: number,
    message: string,
    public details?: Record<string, unknown>
  ) {
    super(message);
    this.name = 'AppError';
  }
}

/**
 * Validation error
 */
export class ValidationError extends AppError {
  constructor(message: string, details?: Record<string, string[]>) {
    super(400, message, details);
    this.name = 'ValidationError';
  }
}

/**
 * Authorization error
 */
export class AuthorizationError extends AppError {
  constructor(message: string = 'Not authorized') {
    super(403, message);
    this.name = 'AuthorizationError';
  }
}

/**
 * Not found error
 */
export class NotFoundError extends AppError {
  constructor(resource: string) {
    super(404, `${resource} not found`);
    this.name = 'NotFoundError';
  }
}

/**
 * Conflict error
 */
export class ConflictError extends AppError {
  constructor(message: string) {
    super(409, message);
    this.name = 'ConflictError';
  }
}

// ============================================
// UTILITY TYPES
// ============================================

/**
 * Pagination options
 */
export interface PaginationOptions {
  page: number;
  limit: number;
  skip: number;
}

/**
 * Paginated result
 */
export interface PaginatedResult<T> {
  items: T[];
  total: number;
  page: number;
  limit: number;
  hasMore: boolean;
}

/**
 * Cache entry
 */
export interface CacheEntry<T> {
  data: T;
  timestamp: number;
  ttl: number;
}

/**
 * User connection info
 */
export interface UserConnectionInfo {
  userId: string;
  socketId: string;
  userEmail: string;
  connectedAt: number;
  isOnline: boolean;
}

// ============================================
// CONFIG TYPES
// ============================================

/**
 * Message limits config
 */
export interface MessageLimitsConfig {
  maxMessageLength: number;
  maxEditWindow: number;
  maxDeleteWindow: number;
}

/**
 * WebSocket config
 */
export interface WebSocketConfig {
  messageLimits: MessageLimitsConfig;
  reconnectDelay: number;
  heartbeatInterval: number;
}

// ============================================
// VALIDATION TYPES
// ============================================

/**
 * Message validation result
 */
export interface ValidationResult {
  valid: boolean;
  errors?: string[];
}

/**
 * Email validation result
 */
export interface EmailValidationResult {
  valid: boolean;
  error?: string;
}

/**
 * Content validation result
 */
export interface ContentValidationResult {
  valid: boolean;
  reason?: string;
  length?: number;
}
